name: simple

services:
  app:
    image: azizjuliansyah/simple-app
    build: .
    ports:
      - "8005:3000"
    restart: always
    volumes:
      - vol-app:/app/public/images

volumes:
  - vol-app: